# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - arm_group2_controller

  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory   # <== 必须加！接头暗号
    default: true
    joints:
      - big_arm_revolute_joint
      - small_arm_revolute_joint
  arm_group2_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory   # <== 必须加！接头暗号
    default: true
    joints:
      - big_arm_revolute_joint2